#!/usr/bin/env bash
# Patch × bk2 cross-reference.
#
# Reads:
#   - tests/fixtures/demos/bk2/*.hits.txt  (per-bk2 invocation lists,
#     generated by tools/build_bk2_coverage.sh)
#   - asm/*.s (.ifndef DECOMP_<sym>)        (patchable function set)
#
# Outputs:
#   - build/patch_bk2_xref.csv  (machine-readable cross-reference)
#   - build/patch_bk2_xref.md   (human-readable table)
#
# CSV columns:
#   N,patch,coldboot,intro,intro_to_end_tutorial,any
#   where each bk2 column is the hit count (0 = unexercised)
set -u
cd "$(git rev-parse --show-toplevel)"

mkdir -p build
CSV=build/patch_bk2_xref.csv
MD=build/patch_bk2_xref.md

# Patch list — every `.ifndef DECOMP_<sym>` in asm/*.s, alphabetic.
grep -hoE "\.ifndef DECOMP_\S+" asm/*.s | sed 's/.*DECOMP_//' | sort -u \
  > /tmp/canonical_xref.txt
TOTAL=$(wc -l < /tmp/canonical_xref.txt)
echo "Loaded $TOTAL patchable functions."

# Build per-bk2 name → hits map.
BK2S=(coldboot intro intro_to_end_tutorial)
for stem in "${BK2S[@]}"; do
  hits=tests/fixtures/demos/bk2/$stem.hits.txt
  if [ ! -s "$hits" ]; then
    echo "Missing $hits — run tools/build_bk2_coverage.sh first."
    exit 1
  fi
  # name → hits (4th column from end: addr  hits  calls  exits  name)
  awk '/^0x/ { print $NF "\t" $2 }' "$hits" \
    > /tmp/bk2_${stem}_hits.tsv
done

# Emit CSV.
{
  echo "N,patch,coldboot,intro,intro_to_end_tutorial,any"
  N=0
  while IFS= read -r patch; do
    N=$((N + 1))
    cb=$(grep -P "^${patch}\t" /tmp/bk2_coldboot_hits.tsv 2>/dev/null | awk '{print $2}')
    in=$(grep -P "^${patch}\t" /tmp/bk2_intro_hits.tsv 2>/dev/null | awk '{print $2}')
    tu=$(grep -P "^${patch}\t" /tmp/bk2_intro_to_end_tutorial_hits.tsv 2>/dev/null | awk '{print $2}')
    cb=${cb:-0}
    in=${in:-0}
    tu=${tu:-0}
    any=$((cb + in + tu))
    echo "$N,$patch,$cb,$in,$tu,$any"
  done < /tmp/canonical_xref.txt
} > "$CSV"

# Emit MD summary.
{
  echo "# Patch × bk2 cross-reference"
  echo
  echo "Hit counts per (patch, bk2). 0 = patch not exercised in that bk2."
  echo "Patch is *not validated* by a bk2 it doesn't exercise — last-frame"
  echo "PPM PASS in that case only confirms the build links cleanly."
  echo
  echo "| # | patch | coldboot | intro | tutorial | total |"
  echo "|---|---|---|---|---|---|"
  awk -F, 'NR > 1 {
    printf "| %d | %s | %d | %d | %d | %d |\n", $1, $2, $3, $4, $5, $6
  }' "$CSV"
  echo
  echo "## Summary"
  echo
  N=$(awk -F, 'NR > 1' "$CSV" | wc -l)
  any=$(awk -F, 'NR > 1 && $6 > 0' "$CSV" | wc -l)
  cb=$(awk -F, 'NR > 1 && $3 > 0' "$CSV" | wc -l)
  in=$(awk -F, 'NR > 1 && $4 > 0' "$CSV" | wc -l)
  tu=$(awk -F, 'NR > 1 && $5 > 0' "$CSV" | wc -l)
  echo "- Total patches: **$N**"
  echo "- Exercised by any bk2: **$any** ($((any*100/N))%)"
  echo "- Exercised by coldboot: **$cb** ($((cb*100/N))%)"
  echo "- Exercised by intro: **$in** ($((in*100/N))%)"
  echo "- Exercised by intro_to_end_tutorial: **$tu** ($((tu*100/N))%)"
  echo "- Not exercised by any bk2: **$((N - any))** ($((100 - any*100/N))%)"
} > "$MD"

echo
echo "Wrote: $CSV  $(wc -l < "$CSV") rows"
echo "Wrote: $MD"
echo
echo "Quick summary:"
tail -10 "$MD"
